// Trail data
export const trailsSeedData = [
  {
    name: 'Black Lightning',
    description: 'Signature downhill track at Winterberg featuring technical rock gardens and big drops',
    bikePark: 'Bikepark Winterberg',
    difficulty: 'expert',
    type: 'downhill',
    length: 2.8,
    elevation: {
      gain: 0,
      loss: 450,
    },
    features: ['Rock Gardens', 'Drops', 'Gap Jumps', 'Technical Sections'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.8,
  },
  {
    name: 'Flow Country',
    description: 'Smooth, flowing trail perfect for beginners and intermediates',
    bikePark: 'Bikepark Winterberg',
    difficulty: 'beginner',
    type: 'flow',
    length: 4.2,
    elevation: {
      gain: 0,
      loss: 320,
    },
    features: ['Berms', 'Small Jumps', 'Rollers', 'Wide Track'],
    status: 'open',
    conditions: {
      current: 'excellent',
      lastUpdated: new Date(),
    },
    rating: 4.7,
  },
  {
    name: 'Geisskopf DH',
    description: 'World Cup level downhill track with multiple line choices',
    bikePark: 'Bikepark Geisskopf',
    difficulty: 'expert',
    type: 'downhill',
    length: 2.1,
    elevation: {
      gain: 0,
      loss: 520,
    },
    features: ['Rock Gardens', 'Step-downs', 'Gap Jumps', 'North Shore'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.9,
  },
  {
    name: 'Forest Flow',
    description: 'Natural single track through dense Bavarian forest',
    bikePark: 'Bikepark Geisskopf',
    difficulty: 'intermediate',
    type: 'enduro',
    length: 5.6,
    elevation: {
      gain: 50,
      loss: 480,
    },
    features: ['Natural Obstacles', 'Root Sections', 'Berms', 'Small Drops'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.6,
  },
  {
    name: 'Harz Lightning',
    description: 'Fast and technical track through the Harz mountains',
    bikePark: 'Bikepark Harz',
    difficulty: 'expert',
    type: 'technical',
    length: 2.4,
    elevation: {
      gain: 0,
      loss: 380,
    },
    features: ['Rock Gardens', 'Step-downs', 'Technical Sections', 'Drops'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.7,
  },
  {
    name: 'Green Monster',
    description: 'Beginner-friendly trail with progressive features',
    bikePark: 'Bikepark Harz',
    difficulty: 'beginner',
    type: 'flow',
    length: 3.8,
    elevation: {
      gain: 0,
      loss: 280,
    },
    features: ['Table Tops', 'Berms', 'Rollers', 'Small Drops'],
    status: 'open',
    conditions: {
      current: 'excellent',
      lastUpdated: new Date(),
    },
    rating: 4.5,
  },
  {
    name: 'Black Forest Express',
    description: 'High-speed track through the Black Forest',
    bikePark: 'Bikepark Todtnau',
    difficulty: 'expert',
    type: 'downhill',
    length: 2.9,
    elevation: {
      gain: 0,
      loss: 460,
    },
    features: ['Gap Jumps', 'Rock Gardens', 'High-Speed Sections', 'Drops'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.8,
  },
  {
    name: 'Todtnau Flow',
    description: 'Smooth flow trail with progressive jumps',
    bikePark: 'Bikepark Todtnau',
    difficulty: 'intermediate',
    type: 'flow',
    length: 4.1,
    elevation: {
      gain: 0,
      loss: 340,
    },
    features: ['Table Tops', 'Berms', 'Step-ups', 'Wall Rides'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.6,
  },
  {
    name: 'Willingen Pro Line',
    description: 'Professional-level jump line with massive features',
    bikePark: 'Bikepark Willingen',
    difficulty: 'expert',
    type: 'jump',
    length: 1.2,
    elevation: {
      gain: 0,
      loss: 180,
    },
    features: ['Big Jumps', 'Step-ups', 'Step-downs', 'Drops'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.9,
  },
  {
    name: 'Freeride Paradise',
    description: 'Creative freeride line with multiple options',
    bikePark: 'Bikepark Willingen',
    difficulty: 'expert',
    type: 'technical',
    length: 2.6,
    elevation: {
      gain: 0,
      loss: 320,
    },
    features: ['Natural Hits', 'Drops', 'Hip Jumps', 'Wood Features'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.7,
  },
  {
    name: 'Bad Wildbad DH',
    description: "One of Germany's most technical downhill tracks",
    bikePark: 'Bikepark Bad Wildbad',
    difficulty: 'expert',
    type: 'downhill',
    length: 1.9,
    elevation: {
      gain: 0,
      loss: 420,
    },
    features: ['Rock Gardens', 'Technical Sections', 'Steep Chutes', 'Drops'],
    status: 'open',
    conditions: {
      current: 'challenging',
      lastUpdated: new Date(),
    },
    rating: 4.9,
  },
  {
    name: 'Wild Child',
    description: 'Intermediate jump line with progressive features',
    bikePark: 'Bikepark Bad Wildbad',
    difficulty: 'intermediate',
    type: 'jump',
    length: 2.8,
    elevation: {
      gain: 0,
      loss: 310,
    },
    features: ['Table Tops', 'Step-ups', 'Berms', 'Small Gaps'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.5,
  },
  {
    name: 'Gravity Express',
    description: 'Fast and flowy downhill track',
    bikePark: 'Bikepark Ochsenkopf',
    difficulty: 'expert',
    type: 'downhill',
    length: 2.3,
    elevation: {
      gain: 0,
      loss: 390,
    },
    features: ['High-Speed Sections', 'Jumps', 'Berms', 'Technical Sections'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.7,
  },
  {
    name: 'Nature Trail',
    description: 'Natural single track with minimal artificial features',
    bikePark: 'Bikepark Ochsenkopf',
    difficulty: 'intermediate',
    type: 'enduro',
    length: 4.7,
    elevation: {
      gain: 80,
      loss: 420,
    },
    features: ['Natural Obstacles', 'Root Sections', 'Rock Gardens', 'Stream Crossings'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.6,
  },
  {
    name: 'Progression Line',
    description: 'Perfect trail for improving jumping skills',
    bikePark: 'Bikepark Schöneck',
    difficulty: 'intermediate',
    type: 'jump',
    length: 3.2,
    elevation: {
      gain: 0,
      loss: 280,
    },
    features: ['Progressive Jumps', 'Table Tops', 'Berms', 'Small Gaps'],
    status: 'open',
    conditions: {
      current: 'excellent',
      lastUpdated: new Date(),
    },
    rating: 4.5,
  },
  {
    name: 'Skills Area',
    description: 'Dedicated skills training area with various features',
    bikePark: 'Bikepark Schöneck',
    difficulty: 'beginner',
    type: 'skills',
    length: 0.8,
    elevation: {
      gain: 0,
      loss: 40,
    },
    features: ['Balance Features', 'Small Drops', 'Pump Track', 'Practice Areas'],
    status: 'open',
    conditions: {
      current: 'excellent',
      lastUpdated: new Date(),
    },
    rating: 4.4,
  },
  {
    name: 'Night Rider',
    description: 'Illuminated evening trail with flow features',
    bikePark: 'Bikepark Hahnenklee',
    difficulty: 'intermediate',
    type: 'flow',
    length: 2.6,
    elevation: {
      gain: 0,
      loss: 290,
    },
    features: ['Lit Track', 'Table Tops', 'Berms', 'Rollers'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.6,
  },
  {
    name: 'Harz Enduro',
    description: 'Long enduro track with varied terrain',
    bikePark: 'Bikepark Hahnenklee',
    difficulty: 'expert',
    type: 'enduro',
    length: 6.2,
    elevation: {
      gain: 120,
      loss: 580,
    },
    features: ['Technical Climbs', 'Fast Descents', 'Natural Features', 'Rock Gardens'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.8,
  },
  {
    name: 'Family Line',
    description: 'Super beginner-friendly trail for first-timers',
    bikePark: 'Bikepark Winterberg',
    difficulty: 'beginner',
    type: 'flow',
    length: 1.8,
    elevation: {
      gain: 0,
      loss: 120,
    },
    features: ['Wide Track', 'Small Rollers', 'Gentle Berms', 'Rest Areas'],
    status: 'open',
    conditions: {
      current: 'excellent',
      lastUpdated: new Date(),
    },
    rating: 4.5,
  },
  {
    name: 'Pro Jump Line',
    description: 'Competition-level slopestyle course',
    bikePark: 'Bikepark Winterberg',
    difficulty: 'expert',
    type: 'jump',
    length: 0.9,
    elevation: {
      gain: 0,
      loss: 140,
    },
    features: ['Big Air Jumps', 'Step-ups', 'Step-downs', 'Hip Jumps'],
    status: 'open',
    conditions: {
      current: 'good',
      lastUpdated: new Date(),
    },
    rating: 4.9,
  },
];

